name: news_uit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.3
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/qcdt.pdf
    - lib/assets/qtsv.pdf
